#!/usr/bin/env bash

echo "Running pre-commit checks..."
if ! npm exec lint-staged; then
  echo "Prettier formatting failed. Fix the issues above and try again."
  exit 1
fi

echo "Pre-commit checks passed."
exit 0
